name: Test Context

on:
  push:
    branches:
      - master

jobs:
  build:
    name: On Push to Master
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Current Directory
        run: echo ${PWD}

      - name: Temp Directory
        run: echo ${{ runner.temp }}

      - name: Workspace Directory
        run: echo ${{ github.workspace }}

      - name: Workspace Directory ENV
        run: echo ${GITHUB_WORKSPACE}

      - name: Home Directory ENV
        run: echo ${HOME}

      - name: List Files
        run: find ${HOME}
